# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-TableTiler
version:      1.16
version_from: 
installdirs:  site
requires:
    HTML::PullParser:              1.0
    IO::Util:                      1.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
